CREATE DATABASE DUNIAMUSIK;

CREATE TABLE DMUSER(
	ID_USER char(8),
    EMAIL varchar(16),
    PASSW varchar(12),
    PRIMARY KEY(ID_USER)
);

CREATE TABLE ARTIST(
    ID_ARTIST char(8),
    NAMA_ARTIST varchar(30),
    LABEL_MUSIK varchar(30) null,
    JUMLAH_STREAM int null,
    PRIMARY KEY(ID_ARTIST)
);

CREATE TABLE LAGU(
    ID_PUBLISH char(8),
    JUDUL varchar(30),
    GENRE varchar(20) null,
    TGL_PUBLISH date,
    ID_ARTIST varchar(8),
    JUMLAH_STREAM int null,
    JUMLAH_SHARE int null,
    JUMLAH_DOWNLOAD int null,
    JUMLAH_FAV int null,
    PRIMARY KEY(ID_PUBLISH),
    FOREIGN KEY(ID_ARTIST) REFERENCES ARTIST(ID_ARTIST)
);

CREATE TABLE FAVORIT(
	ID_FAV char(12),
    ID_PUBLISH char(8),
    ID_USER char(8),
    PRIMARY KEY(ID_FAV),
    FOREIGN KEY(ID_PUBLISH) REFERENCES LAGU(ID_PUBLISH),
    FOREIGN KEY(ID_USER) REFERENCES DMUSER(ID_USER)
);

CREATE TABLE ALBUM(
	ID_ALBUM char(8),
    NAMA_ALBUM varchar(30),
    JUMLAH_LAGU int,
    TGL_PUBLISH date,
    ID_ARTIST char(8),
    ID_PUBLISH char(8),
    PRIMARY KEY(ID_ALBUM),
    FOREIGN KEY(ID_ARTIST) REFERENCES ARTIST(ID_ARTIST)
);

CREATE TABLE PLAYLIST(
	ID_PLAYLIST char(8),
    NAMA_PLAYLIST varchar(20),
    ID_PUBLISH char(8),
    PRIMARY KEY(ID_PLAYLIST),
    FOREIGN KEY(ID_PUBLISH) REFERENCES LAGU(ID_PUBLISH)
);